apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pvc-twenty
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-twenty
spec:
  replicas: 2
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clear-nginx-deployment
spec:
  selector:
    matchLabels:
      app: clear-nginx
  template:
    metadata:
      labels:
        app: clear-nginx
    spec:
      containers:
      - name: clear-nginx
        image: nginx:1.14.2
        volumeMounts:
        - mountPath: /var/www/html
          name: site-data
        ports:
        - containerPort: 80
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: demo-pvc-twenty
