apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnet
  name: aspnet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
    spec:
      containers:
      - image: mcr.microsoft.com/dotnet/framework/aspnet:4.8
        name: aspnet
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: aspnet
  type: NodePort
