apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello1010
  name: nginx-deployment
  labels:
    app: nginx-rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rancher
  template:
    metadata:
      labels:
        app: nginx-rancher
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
