
apiVersion: v1
kind: Service
metadata:
  name: nginx-project
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: rancher/hello-world
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellohello
  namespace: hello
spec:
  rules:
    - host: ${ .ClusterValues.worker}.sslip.io
      http:
        paths:
          - backend:
              service:
                name: nginx-project
                port:
                  number: 80
            path: /hello01
            pathType: Prefix
